QuanLySTK_proj/QuanLySTK/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('home/<str:username>/', include('normal_site.urls')),
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('adsite/', include('admin_site.urls')),
]

QuanLySTK_proj/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.signin, name='signin'),
    path('reset_password', views.reset_password, name='reset_password'),
    path('signup', views.signup, name='signup'),
    # path('change-password', views.MyPasswordChangeView.as_view(), name='change_password'),
    path('logout',views.logout, name='logout'),
]

QuanLySTK_proj/normal_site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'normal_site'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('profile/', views.profile, name='profile'),
    path('lap_phieu_tiet_kiem/', views.LapPhieuTietKiem.as_view(), name='lap_phieu_tiet_kiem'),
    path('tim_kiem_phieu_tiet_kiem/', views.TimKiemPhieuTietKiem.as_view(), name='tim_kiem_phieu_tiet_kiem'),
    path('rut_phieu_tiet_kiem/<str:maptk>', views.RutPhieuTietKiem.as_view(), name='rut_phieu_tiet_kiem'),
    #path('tra_cuu/',views.TraCuu.as_view(), name='tra_cuu'),
    path('tra_cuu_2/',views.tracuu, name='tra_cuu'),
    path('thong_ke/',views.ThongKe,name='thong_ke'),
    path('logout/', views.logout, name='logout')
    ]

QuanLySTK_proj/normal_site/models.py
from django.db import models

# Create your models here.

QuanLySTK_proj/normal_site/forms.py
from django import forms

class PhieuTietKiemForm (forms.Form):
    tenkh = forms.CharField(label='Tên Khách Hàng',max_length=50,required=True)
    CMND = forms.CharField(label='CMND',max_length=12,required=True)
    diachi = forms.CharField(label='Địa Chỉ',max_length=50,required=True)
    sotiengoi =forms.DecimalField(label='Số Tiền Gởi',max_digits=13,decimal_places=2,required=True)
    loaitietkiem =forms.ChoiceField(label='Loại Tiết Kiệm',choices=[('Option 1','Không Kỳ Hạn'),('Option 2','Kỳ Hạn 3 Tháng'),('Option 3','Kỳ Hạn 6 Tháng')],required=True) # chưa đúng lắm

class TimKiemPhieuTietKiemForm (forms.Form):
    tenkh = forms.CharField(label='Tên Khách Hàng',max_length=50,required=True)
    maptk = forms.CharField(label='Mã Phiếu Tiết Kiệm', max_length=10,required=True)

QuanLySTK_proj/normal_site/views.py
from pyexpat import model # ???
from django.http import HttpResponse
from django.shortcuts import render, redirect
import six
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import user_passes_test, login_required, permission_required # add login and permission required decorator
from django.contrib.auth.mixins import PermissionRequiredMixin,LoginRequiredMixin # add login and permission mixin 
from django.views.generic.base import View
from django.db.models import Sum, Count
from admin_site import models 
from . import filters
from django.contrib import messages
from datetime import datetime, date
import calendar
from dateutil.relativedelta import *
from django.contrib.auth import logout as auth_logout

decorator_with_arguments = lambda decorator: lambda *args, **kwargs: lambda func: decorator(func, *args, **kwargs)

@decorator_with_arguments
def custom_permission_required(function, perm):
    def _function(request, *args, **kwargs):
        if request.user.has_perm(perm):
            return function(request, *args, **kwargs)
        else:
            messages.error(request, 'Bạn không có quyền truy cập vào trang này')
            return redirect('normal_site:home',username=kwargs['username'])
    return _function

class UserAccessMixin (PermissionRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:signin')
        
        if not self.has_permission():
            messages.error(request, 'Bạn không có quyền truy cập vào trang này')
            return redirect('normal_site:home',username=kwargs['username'])

        return super(UserAccessMixin, self).dispatch(request, *args, **kwargs)


class Home(View,LoginRequiredMixin):
    login_url = 'accounts:signin'
    redirect_field_name = 'hollaback'
    raise_exception = True

    def get(self,request,username):
        try :
            user = models.User.objects.get(username=username)
        except :
            user = None
        
        if user is not None:
            position=user.groups.all().values()[0]['name']
            if position =='NhanVien':
                context = {'user': user,'position':'Nhân Viên'}
            elif position =='GiamDoc':
                context = {'user': user,'position':'Giám Đốc'}
            else:
                context = {'user': user,'position':'Nhân Viên Phân Tích Dữ Liệu'}
            return render(request,"normal_site/Home/home.html",context)
        else :
            return render(request,"normal_site/Home/home.html")
    # def get(self, request, *args, **kwargs): # Chưa hiểu đoạn này để làm gì luôn
        # return render(request, 'normal_site/Home/home.html')

@login_required()
def profile(request,username):
    user = models.User.objects.get(username=username)
    manv = models.UsersExtendClass.objects.get(user_id=user.id).manv
    position=user.groups.all().values()[0]['name']
    if position=='NhanVien':
            context = {'user': user,'position':'Nhân Viên','manv':manv}
    elif position=='GiamDoc':
            context = {'user': user,'position':'Giám Đốc','manv':manv}
    else:
            context = {'user': user,'position':'Nhân Viên Phân Tích Dữ Liệu','manv':manv}
    if request.method == 'POST':
        btnAddMore = request.POST.get('btnAddMore')
        if btnAddMore == 'Logout':
            return redirect('accounts:logout')
    return render(request,"normal_site/Profile/profile.html",context)

@login_required()
def logout(request):
    auth_logout(request)
    return HttpResponse("Logout thành công!")

class LapPhieuTietKiem(UserAccessMixin, View):
    raise_exception = False
    permission_required = 'admin_site.add_phieutietkiem'

    model = models.Phieutietkiem
    template_name = 'normal_site/PhieuTK/phieutk.html'

    def get(self, request, *args, **kwargs):
        ltk = models.Loaitietkiem.objects.all()
        ltk_list = []

        for i in range(len(ltk)):
            ltk_list.append(ltk[i].ltk)

        date_today = str(date.today())

        context = {'ltk': ltk_list, 'date': date_today}

        return render(request,self.template_name,context)
    
    def post(self, request, *args, **kwargs):
        # lấy thông tin từ request
        id = request.POST.get('id')
        tenkh = request.POST.get('tenkh')
        tenkh = tenkh.title()
        CMND = request.POST.get('CMND')
        diachi = request.POST.get('diachi')
        sotiengoi = request.POST.get('sotiengoi')
        loaitietkiem = request.POST.get('loaitietkiem',False)
        username = kwargs.get('username')

        # check từng thông tin một (1: Thông tin khách hàng, 2: Số tiền tối thiểu)
        # (1)
        if id != '':
            khachhang = models.Khachhang.objects.filter(makh=id)
            if len(khachhang)!=0:
                if (tenkh != khachhang[0].tenkh or CMND != khachhang[0].cccd) :
                    messages.error(request, 'Thông tin khách hàng (Tên hoặc CCCD) không đúng với dữ liệu trong cơ sở dữ liệu')
                    return redirect('normal_site:lap_phieu_tiet_kiem',username=username)
            else: 
                messages.error(request, 'Khách hàng không tồn tại')
                return redirect('normal_site:lap_phieu_tiet_kiem',username=username)
        
        else :
            if (len(CMND)!=9 and len(CMND)!=12):
                messages.error(request,"CMND không hợp lệ" + str(len(CMND)))
                return redirect('normal_site:lap_phieu_tiet_kiem',username=username)
            else :
                khachhang = models.Khachhang.objects.filter(cccd=CMND)
                if len(khachhang)!=0:
                    if (tenkh != khachhang[0].tenkh) :
                        messages.error(request, 'CCCD đã tồn tại trong cơ sở dữ liệu và tên khách hàng đang nhập không khớp với CCCD đã tồn tại')
                        return redirect('normal_site:lap_phieu_tiet_kiem',username=username)
                    else:
                        messages.error(request, 'CCCD và tên khách hàng đã tồn tại trong cơ sở dữ liệu vui lòng nhập thêm ID khách hàng')
                        return redirect('normal_site:lap_phieu_tiet_kiem',username=username)

        # (2)
        sotiengoitoithieu = models.Loaitietkiem.objects.get(ltk=loaitietkiem).sotiengoitoithieu
        if (float(sotiengoi) < sotiengoitoithieu):
            messages.error(request,"Số tiền gởi phải lớn hơn hoặc bằng {}".format(sotiengoitoithieu))
            return redirect('normal_site:lap_phieu_tiet_kiem',username=username)


        # oke thì lưu lại -> 2 hướng (1: nếu khách hàng có thông tin rồi thì chỉ lưu vào bảng phieutietkiem; 2: ngược lại)
        if id != '': # đã có nhập id => Khách hàng đã đăng ký tài khoản
            phieutietkiem = models.Phieutietkiem.objects.create(maptk='PTK' + str(int(models.Thamso.objects.get(tenthamso='SLPhieuTietKiem').giatri)+1),
            makh=models.Khachhang.objects.get(makh=id),
            maltk=models.Loaitietkiem.objects.get(ltk=loaitietkiem),
            sotiengoi=sotiengoi,ngaymophieu=str(date.today()),
            ngaydongphieu=None,sodu=sotiengoi,tinhtrang=1)
            phieutietkiem.save()
        
            # cập nhật tham số SLPhieuTietKiem
            models.Thamso.objects.filter(tenthamso='SLPhieuTietKiem').update(giatri=str(int(models.Thamso.objects.get(tenthamso='SLPhieuTietKiem').giatri)+1))

            messages.success(request, 'Lập phiếu tiết kiệm thành công')
            return redirect('normal_site:lap_phieu_tiet_kiem',username=username)
        
        else:
            khachhang_save = models.Khachhang.objects.create(makh='KH' + str(int(models.Thamso.objects.get(tenthamso='SLKhachHang').giatri)+1),
            tenkh=tenkh,diachi=diachi,cccd=CMND)

            khachhang_save.save()

            phieutietkiem = models.Phieutietkiem.objects.create(maptk='PTK' + str(int(models.Thamso.objects.get(tenthamso='SLPhieuTietKiem').giatri)+1),
            makh=khachhang_save,
            maltk=models.Loaitietkiem.objects.get(ltk=loaitietkiem),
            sotiengoi=sotiengoi,ngaymophieu=str(date.today()),
            ngaydongphieu=None,sodu=sotiengoi,tinhtrang=1)
            phieutietkiem.save()

            # cập nhật tham số SLPhieuTietKiem và SLKhachHang
            models.Thamso.objects.filter(tenthamso='SLPhieuTietKiem').update(giatri=str(int(models.Thamso.objects.get(tenthamso='SLPhieuTietKiem').giatri)+1))
            models.Thamso.objects.filter(tenthamso='SLKhachHang').update(giatri=str(int(models.Thamso.objects.get(tenthamso='SLKhachHang').giatri)+1))

            messages.success(request, 'Lập phiếu tiết kiệm thành công')
            return redirect('normal_site:lap_phieu_tiet_kiem',username=username)

# class TraCuu(View, LoginRequiredMixin):
#     # LoginRequiredMixin
#     login_url = 'accounts:signin'
#     redirect_field_name = 'hollaback'
#     raise_exception = True

#     template_name = 'normal_site/Tracuu/tra_cuu.html'

#     def post(self, request, *args, **kwargs):
#         query = request.POST.get('q')
#         ptk = models.Phieutietkiem.objects.filter(makh=query)
        
#         if len(ptk) == 0:
#             messages.error(request, 'Không tìm thấy phiếu tiết kiệm nào hoặc thông tin không đúng')
#             return redirect('normal_site:tra_cuu')
#         else:
#             context = {'ptk':ptk,'query':query}
#             return render(request, self.template_name, context)

#     def get(self, request, *args, **kwargs):
#         return render(request, self.template_name)

@login_required()
def tracuu(request, *args, **kwargs):
    ptk = models.Phieutietkiem.objects.all()

    orders = ptk.order_by('ngaymophieu')
    order_count = orders.count()

    myFilter = filters.PhieutietkiemFilter(request.GET, queryset=orders)
    orders = myFilter.qs

    context = {'ptk':ptk,'orders':orders,'order_count':order_count,'myFilter':myFilter}

    return render(request, 'normal_site/Tracuu/tra_cuu_2.html', context)

QuanLySTK_proj/templates/normal_site/Tracuu/tra_cuu.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tra cứu</title>
    <link rel="stylesheet" href="{% static 'css/tra_Cuu.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer_header.css' %}">
</head>

<body>
    <!-- Header -->
    <div class="homeHeader">
        <div class="homeHeaderLogo">
            <p>UIT SAVE</p>
            <img src="https://wp-tid.zillowstatic.com/trulia/wp-content/uploads/sites/3/2019/03/Tips-for-saving-to-buy-a-house-12a08b-1024x512.jpg"
                alt="" />
        </div>
        <div class="homeHeaderUser">
            <a href="{%url 'normal_site:profile' user.username%} ">
                <div class="infoUser">
                    <p class="username">{{user.username}}</p>
                    <p class="positon">{{position}}</p>
                </div>
                <div class="logoUser">
                    <img src="https://banner2.cleanpng.com/20180716/lra/kisspng-logo-person-user-person-icon-5b4d2bd2236ca6.6010202115317841461451.jpg"
                        alt="">
                </div>
            </a>
        </div>
    </div>
    <div class="homeBody">
        {% for message in messages %}

        <div class="alert alert-success">
            <a class="close" href="#" data-dismiss="alert">×</a>
            {{ message }}
        </div>

        {% endfor %}

        <div class="content-container">
            <div class="wrapper">
                <h1 class="title">Tra cứu</h1>
                <hr>
                <div class="search-area">
                    <form method="POST" action="/home/tra_cuu/">
                        {% csrf_token %}
                        <input type='text' name="q" placeholder='Nhập ID Khách Hàng' required=True>
                        <button type="submit">Tìm Kiếm</button>
                    </form>
                </div>
                {% if query %}
                <table>
                    <tr class="first-row-header">
                        <th colspan="5">Danh sách phiếu tiết kiệm</th>
                    </tr>
                    <tr class="second-row-header">
                        <th class="stt">STT</th>
                        <th class="ms">Mã số</th>
                        <th class="ltk">Loại tiết kiệm</th>
                        <th class="kh">Khách hàng</th>
                        <th class="sd">Số dư</th>
                    </tr>
                    <div class="table-row-data">
                        {% for item in ptk %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{item.maptk}}</td>
                            <td>{{item.maltk.ltk}}</td>
                            <td>{{item.makh.tenkh}}</td>
                            <td>{{item.sodu}}</td>
                        </tr>
                        {% endfor %}
                    </div>
                </table>
                {% endif %}
            </div>
        </div>
    </div>

    <!-- <div class="footer-container">
        <div class="wrapper">
            Footer
        </div>
    </div> -->

    <div class="homeFooter">
        <footer class="footer-distributed">

            <div class="footer-left">

                <h3><span class="homeHeaderLogo"><img
                            src="https://wp-tid.zillowstatic.com/trulia/wp-content/uploads/sites/3/2019/03/Tips-for-saving-to-buy-a-house-12a08b-1024x512.jpg"
                            alt="" /></span></h3>

                <p class="footer-links">
                    <a href="#" class="link-1">Trang Chủ</a>

                    <a href="#">Lập Phiếu Tiết Kiệm</a>

                    <a href="#">Lập Phiếu Rút Tiền</a>

                    <a href="#">Tra Cứu</a>

                    <a href="#">Thống Kê</a>

                </p>

                <p class="footer-company-name">UIT SAVE © 2022</p>
            </div>

            <div class="footer-center">

                <div>
                    <i class="fa fa-map-marker"></i>
                    <p><span>UIT</span>HCM</p>
                </div>

                <div>
                    <i class="fa fa-phone"></i>
                    <p>+84 339 876 802</p>
                </div>

                <div>
                    <i class="fa fa-envelope"></i>
                    <p><a href="mailto:thanhtra1882001@gmail.com">thanhtra1882001@gmail.com</a></p>
                </div>

            </div>

            <div class="footer-right">

                <p class="footer-company-about">
                    <span>About the UIT SAVE</span>
                    An toàn, nhanh chóng, tiện dụng.
                </p>

                <div class="footer-icons">

                    <a href="#" title="fb"><i class="fa fa-facebook"></i></a>
                    <a href="#" title="tw"><i class="fa fa-twitter"></i></a>
                    <a href="#" title="in"><i class="fa fa-linkedin"></i></a>
                    <a href="#" title="gh"><i class="fa fa-github"></i></a>

                </div>

            </div>

        </footer>
    </div>
    <script src="main.js"></script>
</body>

</html>

QuanLySTK_proj/templates/normal_site/Tracuu/tra_cuu_2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tra cứu</title>
    <link rel="stylesheet" href="{% static 'css/tra_Cuu.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer_header.css' %}">
</head>

<body>
    <!-- <div class="header-container">
        <div class="wrapper">
            <nav>
                <div class="logo">
                    Logo
                </div>
                <div class="user">
                    <div class="user-info">
                        <p class="username">User name</p>
                        <p class="id">ID</p>
                    </div>
                    <div class="user-avatar">
                        <img src="{% static 'img/logo.jpg' %}" alt="avatar">
                    </div>
                </div>
            </nav>
        </div>
    </div> -->

    <!-- Header -->
    <div class="homeHeader">
        <div class="homeHeaderLogo">
            <p>UIT SAVE</p>
            <img src="https://wp-tid.zillowstatic.com/trulia/wp-content/uploads/sites/3/2019/03/Tips-for-saving-to-buy-a-house-12a08b-1024x512.jpg"
                alt="" />
        </div>
        <div class="homeHeaderUser">
            <a href="{%url 'normal_site:profile' user.username%} ">
                <div class="infoUser">
                    <p class="username">{{user.username}}</p>
                    <p class="positon">{{position}}</p>
                </div>
                <div class="logoUser">
                    <img src="https://banner2.cleanpng.com/20180716/lra/kisspng-logo-person-user-person-icon-5b4d2bd2236ca6.6010202115317841461451.jpg"
                        alt="">
                </div>
            </a>
        </div>
    </div>
    <div class="homeBody">
        {% for message in messages %}

        <div class="alert alert-success">
            <a class="close" href="#" data-dismiss="alert">×</a>
            {{ message }}
        </div>

        {% endfor %}

        <div class="content-container">
            <div class="wrapper">
                <h1 class="title">Tra cứu</h1>
                <hr>
            </div>

            <div class='search-area' id="search">
                <form method="GET">
                    {{ csrf_field }}
                    {{myFilter.form}}
                    <button class='btn btn-primary' type="submit" id="search">Search</button>
                </form>
            </div>
            <div class="row">
                <div class="col-md">
                    <div class="card card-body">
                        <table class="table table-sm">
                            <tr>
                                <th>STT</th>
                                <th>Mã Phiếu Tiết Kiệm</th>
                                <th>Mã Loại Tiết Kiệm</th>
                                <th>Mã Khách Hàng</th>
                                <th>Số Dư</th>
                            </tr>

                            {% for order in orders %}

                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{order.maptk}}</td>
                                <td>{{order.maltk.ltk}}</td>
                                <td>{{order.makh.tenkh}}</td>
                                <td>{{order.sodu}}</td>
                            </tr>
                            {% endfor %}

                        </table>
                    </div>
                </div>
                <br>
            </div>

        </div>
    </div>

    <div class="homeFooter">
        <footer class="footer-distributed">

            <div class="footer-left">

                <h3><span class="homeHeaderLogo"><img
                            src="https://wp-tid.zillowstatic.com/trulia/wp-content/uploads/sites/3/2019/03/Tips-for-saving-to-buy-a-house-12a08b-1024x512.jpg"
                            alt="" /></span></h3>

                <p class="footer-links">
                    <a href= "{%url 'normal_site:home' user.username %}" class="link-1">Trang Chủ</a>

                    <a href="{%url 'normal_site:lap_phieu_tiet_kiem' user.username %}">Lập Phiếu Tiết Kiệm</a>

                    <a href="{%url 'normal_site:tim_kiem_phieu_tiet_kiem' user.username %}">Lập Phiếu Rút Tiền</a>

                    <a href="{%url 'normal_site:tra_cuu' user.username %}">Tra Cứu</a>

                    <a href="{%url 'normal_site:thong_ke' user.username %}">Thống Kê</a>

                </p>

                <p class="footer-company-name">UIT SAVE © 2022</p>
            </div>

            <div class="footer-center">

                <div>
                    <i class="fa fa-map-marker"></i>
                    <p><span>UIT</span>HCM</p>
                </div>

                <div>
                    <i class="fa fa-phone"></i>
                    <p>+84 339 876 802</p>
                </div>

                <div>
                    <i class="fa fa-envelope"></i>
                    <p><a href="mailto:thanhtra1882001@gmail.com">thanhtra1882001@gmail.com</a></p>
                </div>

            </div>

            <div class="footer-right">

                <p class="footer-company-about">
                    <span>About the UIT SAVE</span>
                    An toàn, nhanh chóng, tiện dụng.
                </p>

                <div class="footer-icons">

                    <a href="#" title="fb"><i class="fa fa-facebook"></i></a>
                    <a href="#" title="tw"><i class="fa fa-twitter"></i></a>
                    <a href="#" title="in"><i class="fa fa-linkedin"></i></a>
                    <a href="#" title="gh"><i class="fa fa-github"></i></a>

                </div>

            </div>

        </footer>
    </div>
    <script src="main.js"></script>
</body>

</html>